### ISSUE TITLE
'HPOpenWeather' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by fabiom91** [Fri3ndlyGerman/OpenWeatherSwift#4]
I get the error in the title when initialising the api key:

```swift
var api = HPOpenWeather(apiKey: OWM_API_KEY)
```

**Comment by henrik-dmg** [comment]
Should be fixed in 3.1.1

**Comment by fabiom91** [comment]
It seems the version available with pod is still the 3.0.0

**Comment by henrik-dmg** [comment]
Just pushed a new version :) let me know if there are any issues (NOTE: I still need to update the documentation)

**Comment by fabiom91** [comment]
Still downloading version 3.0.0 with `pod "HPOpenWeather"` if I try `pod "HPOpenWeather", "3.1.1"`it throws an error

**Comment by fabiom91** [comment]
I kinda fix it by replicating your changes in the last commit: https://github.com/henrik-dmg/HPOpenWeather/commit/a953d448165bb4714511fd91a20657aa9357dbb6

Fortunately they aren't a lot :D

**Comment by henrik-dmg** [comment]
Have you run `pod repo update`? The latest version is shown on [here](https://cocoapods.org/pods/HPOpenWeather)
