### ISSUE TITLE
couldn't make it run with pod install

### ISSUE THREAD

**Issue by luckychris** [Fri3ndlyGerman/OpenWeatherSwift#5]
I just tried to test your library and set up a brand new project, a podfile which successfully installed (at least green message after pod install) but in the project build it says framework not found

![image](https://user-images.githubusercontent.com/232549/84382095-6bf2e980-abea-11ea-9a85-37686b07f2b9.png)

**Comment by henrik-dmg** [comment]
This might be an obvious fix, but did you make sure to open the `.xcworkspace` file after installing pods instead of `.xcproject`?

**Comment by luckychris** [comment]
OMG, sorry ....not my day. Thank you!!!!

**Comment by henrik-dmg** [comment]
No worries at all! :) let me know if you need any additional help
