### ISSUE TITLE
weather data?

### ISSUE THREAD

**Issue by luckychris** [Fri3ndlyGerman/OpenWeatherSwift#6]
i am sorry and hope, i did not make a silly mistake again :( 
i tried this:

 let handler = HPOpenWeather(apiKey: "myAPIKey", temperatureFormat: .celsius, language: .german)
        let request = LocationRequest(CLLocationCoordinate2D(latitude: 49.2938073, longitude:8.639581))
        
        handler.requestDailyForecast(with: request) {  forecast, error in
            
            print (forecast)
            
        }

of course i inserted my right api key (the city was shown right) but i do not get any weather data...and maybe you should update your readme example with configuration because it looks like you changed this to be handled via the constructor of HPOpenWeather....

**Comment by henrik-dmg** [comment]
I will take a closer look at this tonight

**Comment by henrik-dmg** [comment]
I just updated the framework to version `3.2.0`. Please run `pod update` to get the latest changes. I have not update the `README` yet, but to achieve what you were trying above please do the following:
```swift
let settings = HPOpenWeather.Settings(apiKey: "myAPIKey", language: .german, temperatureFormat: .celsius)
let handler = HPOpenWeather(settings: settings)

let request = WeatherRequest(coordinate: CLLocationCoordinate2D(latitude: 49.2938073, longitude:8.639581))
handler.requestWeather(request) { result in
    // Handle result here
}
```
